In [149]:
from asyncio.windows_events import NULL

import pandas as pd
import numpy as np

In [150]:
df = pd.read_csv(r"C:\Users\harsh\Documents\data Analyst Projects\complex_phone_data\data_scraping\final_ds.csv")

In [151]:
df.sample(2)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
53,Samsung Galaxy S25,Snapdragon 8 Elite,12 GB RAM | 256 GB Storage,50 MP + 12 MP + 10 MP Rear Camera,12 MP Front Camera,4000 mAh | 25W Fast Charging,6.2 inches (15.75 cm) | Dynamic AMOLED 2x,"AnTuTu Score 2,185,567","₹66,798"
2239,Samsung Galaxy M31 128GB,Samsung Exynos 9 Octa 9611,6 GB RAM | 128 GB Storage,64 MP + 8 MP + 5 MP + 5 MP Rear Camera,32 MP Front Camera,6000 mAh | 15W Fast Charging,6.4 inches (16.26 cm) | Super AMOLED,"AnTuTu Score 194,497","₹18,000"

## Data Assessing

#### mannual assessing

`brand name`
- data in row 1177 is missing

`processor`
- row no 1494 has nm info in processor

`storage`
- ram and rom both are present in same col /
- row no 62 have type of storage info
- row 2307, 2849, 2952, 2958, 2981, 2982, 2983, 2985, 2986, 2987, 2989, 2993, 2994, 2995, 2996, 2998, 2999, 3000, 4128 , 4211, 4306, 4310,315, 4316, 4322, 4331, 4332, 4334, 4336, 4340, 4342, 4352, 4357, 4358, 4359, 4377, 4379, 4383, 4387, 4389, 4393, 4396, 4398, 4400, 4402, 4403, 4404, 4406, 4407, 4408, 4409, 4412, 4413, 4414, 4415, 4417, 4422, 4423, 4424, 4425, 4426, 4427, 4431, 4450, 4452, 4466, 4467, 4468 have only storage

- row 4025, 4086, 4183, 4204, 4233, 4297, 4305, 4314,
  4420, 4447, 4448, 4456, 4558 have only ram

`battery`
- this col can be split into two 1st battery and 2nd charging speed
- at some places it's directly mentioned 3000 mAh Fast Charging, 3300 mAh Quick Charging, 5000 mAh | 10W Fast Charging

`display`
- it can be split into tow display resolution and display type

`antutu`
- ex - AnTuTu Score 588,319 we can remove the text and comma

`price`
- rupees sign making it as string


**feature engineering**
- we can create a brand_name and brand_model from brand_name col

### programmatic assessing

- all the col are of string type
- no duplicated data

In [152]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   processor     3492 non-null   str
 2   storage       4039 non-null   str
 3   back_camera   4674 non-null   str
 4   fron_camera   3618 non-null   str
 5   battery       4782 non-null   str
 6   display       4798 non-null   str
 7   anTuTu_score  1737 non-null   str
 8   price         4734 non-null   str
dtypes: str(9)
memory usage: 337.6 KB

In [153]:
df.duplicated().sum()

np.int64(0)

In [154]:
df.sample(15)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
3583,Karbonn KX26,NaN,NaN,0.3 MP Rear Camera,NaN,1450 mAh,2.4 inches (6.1 cm) | TFT,NaN,"₹1,290"
794,"Samsung Galaxy A37 5G 256GB, 12GB RAM",Samsung Exynos 1480,12 GB RAM | 256 GB Storage,50 MP + 8 MP + 5 MP Rear Camera,12 MP Front Camera,5000 mAh | 45W,6.7 inches (17.02 cm) | Super AMOLED,"AnTuTu Score 1,053,896","₹51,499"
3062,Snexian Bold 888,NaN,32 MB RAM | 32 MB Storage,1.3 MP Rear Camera,NaN,1000 mAh,1.44 inches (3.66 cm) | TFT,NaN,₹999
1434,Honor 200 Pro,Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 12 MP + 50 MP Rear Camera,50 MP Front Camera,5200 mAh | 100W Super Charging,6.78 inches (17.22 cm) | OLED,"AnTuTu Score 1,278,713","₹57,999"
4195,LG L80,Snapdragon 200,1 GB RAM | 4 GB Storage,5 MP Rear Camera,0.3 MP Front Camera,2540 mAh,5.0 inches (12.7 cm) | IPS LCD,NaN,"₹14,162"
2011,Samsung Galaxy S8,Samsung Exynos 9 Octa 8895,4 GB RAM | 64 GB Storage,12 MP Rear Camera,8 MP Front Camera,3000 mAh Fast Charging,5.8 inches (14.73 cm) | Super AMOLED,NaN,"₹49,990"
558,"vivo V70 Elite 512GB, 12GB RAM",Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 8 MP + 50 MP Rear Camera,50 MP Front Camera,6500 mAh | 90W Flash Charging,6.59 inches (16.74 cm) | AMOLED,"AnTuTu Score 1,815,619","₹61,999"
4101,HTC Desire 820G+ Dual SIM,MediaTek MT6592,1 GB RAM | 16 GB Storage,13 MP Rear Camera,8 MP Front Camera,2600 mAh,5.5 inches (13.97 cm) | IPS LCD,NaN,"₹11,490"
3043,realme P1 256GB,MediaTek Dimensity 7050,8 GB RAM | 256 GB Storage,50 MP + 2 MP Rear Camera,16 MP Front Camera,5000 mAh | 45W Super VOOC Charging,6.67 inches (16.94 cm) | AMOLED,"AnTuTu Score 418,175","₹15,999"
2776,XOLO Era 4X,MediaTek MT6739,1 GB RAM | 16 GB Storage,8 MP Rear Camera,5 MP Front Camera,3000 mAh,5.45 inches (13.84 cm) | IPS LCD,NaN,"₹6,199"
899,Xiaomi Redmi Note 4,Snapdragon 625,4 GB RAM | 64 GB Storage,13 MP Rear Camera,5 MP Front Camera,4100 mAh,5.5 inches (13.97 cm) | IPS LCD,NaN,"₹9,999"
777,realme GT 6 12GB RAM,Snapdragon 8s Gen 3,12 GB RAM | 256 GB Storage,50 MP + 8 MP + 50 MP Rear Camera,32 MP Front Camera,5500 mAh | 120W Super VOOC Charging,6.78 inches (17.22 cm) | LTPO AMOLED,"AnTuTu Score 1,501,830","₹46,890"
519,vivo Y11 5G 128GB,MediaTek Dimensity 6300,4 GB RAM | 128 GB Storage,13 MP + 0.08 MP Rear Camera,5 MP Front Camera,6500 mAh | 15W,6.74 inches (17.12 cm) | LCD,NaN,"₹20,549"
3391,Xiaomi Redmi Note 10 Pro 8GB RAM,Snapdragon 732G,8 GB RAM | 128 GB Storage,64 MP + 8 MP + 5 MP + 2 MP Rear Camera,16 MP Front Camera,5020 mAh | 33W Fast Charging,6.67 inches (16.94 cm) | Super AMOLED,"AnTuTu Score 331,961","₹13,999"
62,Apple iPhone 15,Apple A16 Bionic,6 GB RAM | 128 GB Storage,48 MP + 12 MP Rear Camera,12 MP Front Camera,3349 mAh | 20W Fast Charging,6.1 inches (15.49 cm) | Super Retina XDR,NaN,"₹57,900"

In [155]:
df['price'] = df['price'].str.replace('₹', '').str.replace(',', '')

In [156]:
df['price'] = df['price'].fillna(0).astype(int)

In [157]:
df.sample(1)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
4611,OnePlus Open Apex Edition,Snapdragon 8 Gen 2,16 GB RAM | 1 TB Storage,48 MP + 48 MP + 64 MP Rear Camera,20 MP + 32 MP Front Camera,4805 mAh | 67W Super VOOC Charging,7.82 inches (19.86 cm) | LTPO Flexi-fluid AMOLED,"AnTuTu Score 1,337,767",149999

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   processor     3492 non-null   str
 2   storage       4039 non-null   str
 3   back_camera   4674 non-null   str
 4   fron_camera   3618 non-null   str
 5   battery       4782 non-null   str
 6   display       4798 non-null   str
 7   anTuTu_score  1737 non-null   str
 8   price         4800 non-null   int64
dtypes: int64(1), str(8)
memory usage: 337.6 KB

In [159]:
df1 = df

In [160]:
df[df['fron_camera'].isnull()]['price'].describe()

count     1182.000000
mean      2004.302876
std       2927.946826
min          0.000000
25%        944.250000
50%       1229.500000
75%       1850.000000
max      39999.000000
Name: price, dtype: float64

In [161]:
df[(df['price'] == 35795)&(df['fron_camera'].isnull())]

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2995,Sony Ericsson Xperia X10,Snapdragon S1,384 MB RAM | 1 GB Storage,8.1 MP Rear Camera,NaN,1500 mAh,4 inches (10.16 cm) | LCD,NaN,35795

In [162]:
df.drop(1174, inplace=True)

In [163]:
df[(df['price'] == 39999)&(df['fron_camera'].isnull())]

Empty DataFrame
Columns: [brand_name, processor, storage, back_camera, fron_camera, battery, display, anTuTu_score, price]
Index: []

In [164]:
df[df['fron_camera'].isnull()]['price'].describe()

count     1181.000000
mean      1972.131245
std       2712.142064
min          0.000000
25%        944.000000
50%       1229.000000
75%       1850.000000
max      35795.000000
Name: price, dtype: float64

In [165]:
df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra', 'display'] = df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra','display'
].str.split(':').str[1]

In [166]:
df[df['brand_name'] == 'Motorola Razr 50 Ultra']

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
737,Motorola Razr 50 Ultra,Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 50 MP Rear Camera,32 MP Front Camera,4000 mAh | 45W Turbo Power Charging,"6.9 inches pOLED, 3000 nits, 165 Hz refresh r...","AnTuTu Score 1,408,183",64811

In [167]:
df['display_size'] = df['display'].str.split('|').str[0].str.split(' ').str[0].fillna(0)

In [174]:
df['display_size'] = df['display_size'].replace('','0')

In [175]:
df[df['display_size']=='']

Empty DataFrame
Columns: [brand_name, processor, storage, back_camera, fron_camera, battery, display, anTuTu_score, price, display_size]
Index: []

In [177]:
df['display_size'] = df['display_size'].astype(float)

In [180]:
df = df[df['display_size']>3]

In [186]:
df = df[df['storage'].str.contains('RAM')]

In [184]:
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'storage'] = '12 GB RAM | 256 GB Storage'
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'price'] = 104990

### feature engineering

- we are going to create col such as brand and brand model
- ram and storage from storage col
- primary_rear_camera and no of rear camera from back_camera
- primary_front_camera from fron_camera
- battery_capacity and charging_type from battery col
- display_size and display_type form display col
- exact anTuTu score

In [221]:
def len_of_list(l):
    return len(l)

In [222]:
df['brand'] = df['brand_name'].str.split(' ').str[0]
df['ram'] = df['storage'].str.split('|').str[0].str.split(' ').str[0]
df['storage_capacity'] = df['storage'].str.split('|').str[1].str.split(' ').str[1]
df['primary_rear_camera'] = df['back_camera'].str.split('+').str[0].str.split(' ').str[0]
df['front_camera'] = df['fron_camera'].str.split(' ').str[0]
df['battery_capacity']  = df['battery'].str.split('|').str[0].str.split(' ').str[0]
df['charging_type'] = df['battery'].str.split('|').str[1]
df['display_type'] = df['display'].str.split('|').str[1]
df['antutu_score'] = df['anTuTu_score'].str.split(' ').str[2]

In [223]:

df['camera_count'] = df['back_camera'].str.split('+').apply(len_of_list)

In [225]:
list_old_col = ['storage', 'back_camera', 'fron_camera', 'battery', 'display', 'anTuTu_score']

In [226]:
df = df.drop(columns=list_old_col)

In [227]:
df.sample(5)

,brand_name,processor,price,display_size,brand,ram,storage_capacity,primary_rear_camera,front_camera,battery_capacity,charging_type,display_type,antutu_score,camera_count
2663,Xiaomi Redmi Note 11 4G 128GB,Snapdragon 680,12499,6.43,Xiaomi,6,128,50,13,5000,33W Fast Charging,AMOLED,"269,010",4
1950,Moto E13,Unisoc T606,6999,6.50,Moto,2,64,13,5,5000,10W,IPS LCD,0,1
3077,Itel S23,Unisoc T606,9499,6.60,Itel,8,128,50,8,5000,10W,IPS LCD,NaN,2
2468,Nokia 6.1 (Nokia 6 2018) 64GB,Snapdragon 630,20095,5.50,Nokia,4,64,16,8,3000,NaN,IPS LCD,NaN,1
3389,realme 8 Pro 8GB RAM,Snapdragon 720G,19999,6.40,realme,8,128,108,16,4500,50W Super Dart Charging,Super AMOLED,"286,454",4